# Generated by Django 6.0.1 on 2026-03-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disparo', '0002_alter_campanhadisparo_busca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipAquecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero WhatsApp')),
                ('apelido', models.CharField(blank=True, max_length=50, verbose_name='Apelido (para IA conversar)')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Conexao'), ('conectado', 'Conectado'), ('aquecendo', 'Aquecendo'), ('pronto', 'Pronto para Uso'), ('banido', 'Banido'), ('pausado', 'Pausado')], default='aguardando', max_length=20)),
                ('msgs_enviadas_total', models.IntegerField(default=0)),
                ('msgs_enviadas_hoje', models.IntegerField(default=0)),
                ('msgs_recebidas_total', models.IntegerField(default=0)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('erros_consecutivos', models.IntegerField(default=0)),
                ('persona', models.TextField(blank=True, help_text='Descricao da personalidade para a IA gerar msgs naturais', verbose_name='Persona do chip')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquecimento_chips', to='disparo.instanciawhatsapp')),
            ],
            options={
                'verbose_name': 'Chip em Aquecimento',
                'verbose_name_plural': 'Chips em Aquecimento',
            },
        ),
        migrations.CreateModel(
            name='GrupoAquecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=100)),
                ('group_jid', models.CharField(blank=True, max_length=255, null=True, verbose_name='JID do Grupo')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('instancia_criadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disparo.instanciawhatsapp', verbose_name='Instancia que criou o grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Aquecimento',
                'verbose_name_plural': 'Grupos de Aquecimento',
            },
        ),
        migrations.CreateModel(
            name='ConversaAquecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privado', 'Conversa Privada'), ('grupo', 'Conversa no Grupo')], max_length=10)),
                ('tema', models.CharField(max_length=200, verbose_name='Tema da conversa')),
                ('ativa', models.BooleanField(default=True)),
                ('total_mensagens', models.IntegerField(default=0)),
                ('max_mensagens', models.IntegerField(default=15, verbose_name='Max msgs nesta conversa')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_msg', models.DateTimeField(blank=True, null=True)),
                ('participantes', models.ManyToManyField(related_name='conversas', to='aquecimento.chipaquecimento')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquecimento.grupoaquecimento')),
            ],
            options={
                'verbose_name': 'Conversa de Aquecimento',
                'verbose_name_plural': 'Conversas de Aquecimento',
                'ordering': ['-data_ultima_msg'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAquecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='aquecimento.conversaaquecimento')),
                ('destinatario', models.ForeignKey(blank=True, help_text='Null se for mensagem no grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgs_recebidas_aquecimento', to='aquecimento.chipaquecimento')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_enviadas_aquecimento', to='aquecimento.chipaquecimento')),
            ],
            options={
                'verbose_name': 'Mensagem de Aquecimento',
                'verbose_name_plural': 'Mensagens de Aquecimento',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAquecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('status', models.CharField(choices=[('configurando', 'Configurando'), ('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='configurando', max_length=20)),
                ('msgs_dia_inicio', models.IntegerField(default=3, verbose_name='Msgs/dia no inicio')),
                ('msgs_dia_meta', models.IntegerField(default=200, verbose_name='Meta msgs/dia ao final')),
                ('dias_aquecimento', models.IntegerField(default=21, verbose_name='Dias de aquecimento')),
                ('horario_inicio', models.TimeField(default='08:00')),
                ('horario_fim', models.TimeField(default='21:00')),
                ('habilitar_grupo', models.BooleanField(default=True, verbose_name='Criar grupo entre os chips')),
                ('habilitar_privado', models.BooleanField(default=True, verbose_name='Conversas privadas entre chips')),
                ('delay_minimo', models.IntegerField(default=60, verbose_name='Delay minimo entre msgs (seg)')),
                ('delay_maximo', models.IntegerField(default=300, verbose_name='Delay maximo entre msgs (seg)')),
                ('pausa_min_minutos', models.IntegerField(default=15, verbose_name='Pausa minima (min)')),
                ('pausa_max_minutos', models.IntegerField(default=60, verbose_name='Pausa maxima (min)')),
                ('msgs_antes_pausa', models.IntegerField(default=8, verbose_name='Msgs antes de uma pausa longa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('dia_atual', models.IntegerField(default=0, verbose_name='Dia atual do aquecimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aquecimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Aquecimento',
                'verbose_name_plural': 'Planos de Aquecimento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='grupoaquecimento',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='aquecimento.planoaquecimento'),
        ),
        migrations.AddField(
            model_name='conversaaquecimento',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='aquecimento.planoaquecimento'),
        ),
        migrations.AddField(
            model_name='chipaquecimento',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='aquecimento.planoaquecimento'),
        ),
        migrations.CreateModel(
            name='LogDiarioAquecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('msgs_enviadas', models.IntegerField(default=0)),
                ('msgs_recebidas', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('meta_dia', models.IntegerField(default=0, verbose_name='Meta de msgs para o dia')),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_diarios', to='aquecimento.chipaquecimento')),
            ],
            options={
                'verbose_name': 'Log Diario Aquecimento',
                'verbose_name_plural': 'Logs Diarios Aquecimento',
                'unique_together': {('chip', 'data')},
            },
        ),
    ]
