"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# Vercel sets VERCEL=1 automatically in their environment
IS_VERCEL = os.getenv('VERCEL', '') == '1'
DEBUG = False if IS_VERCEL else os.getenv('DEBUG', 'True').lower() == 'true'

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['buscaleads.site', 'www.buscaleads.site', '.vercel.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'tailwind',
    'theme',
    # Local apps
    'accounts',
    'clientes',
    'disparo',
    'aquecimento',
]

# Context app requires heavy ML dependencies (chromadb, sentence-transformers)
# Only load in development where full requirements are installed
try:
    import chromadb
    INSTALLED_APPS.append('context')
except ImportError:
    pass

if not IS_VERCEL:
    try:
        import django_browser_reload
        if DEBUG:
            INSTALLED_APPS.append('django_browser_reload')
    except ImportError:
        pass

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not IS_VERCEL and DEBUG and 'django_browser_reload' in INSTALLED_APPS:
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

if IS_VERCEL:
    # Vercel: filesystem is read-only, use /tmp for collectstatic
    STATIC_ROOT = '/tmp/staticfiles'
    WHITENOISE_USE_FINDERS = True
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# CSRF trusted origins for production
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'https://buscaleads.site',
        'https://www.buscaleads.site',
        'https://*.vercel.app',
    ]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Apify Configuration
APIFY_API_TOKEN = os.getenv('APIFY_API_TOKEN', '')
APIFY_GOOGLE_MAPS_ACTOR = 'compass/google-maps-extractor'

# Evolution API Configuration (WhatsApp)
EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL', 'http://localhost:8080')
EVOLUTION_API_KEY = os.getenv('EVOLUTION_API_KEY', 'change-me')

# ============================================
# CONTEXT SYSTEM CONFIGURATION
# ============================================

# OpenAI API Key (for embeddings)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ChromaDB persistence directory
CHROMA_PERSIST_DIRECTORY = BASE_DIR / 'chroma_db'

# Context documents directory
CONTEXT_DOCS_DIRECTORY = BASE_DIR / 'docs'

# Embedding model configuration
CONTEXT_EMBEDDING_PROVIDER = os.getenv('CONTEXT_EMBEDDING_PROVIDER', 'openai')  # 'openai' or 'sentence-transformers'
CONTEXT_EMBEDDING_MODEL = os.getenv('CONTEXT_EMBEDDING_MODEL', 'text-embedding-3-small')

# Chunking configuration
CONTEXT_MAX_CHUNK_SIZE = int(os.getenv('CONTEXT_MAX_CHUNK_SIZE', 1000))
CONTEXT_CHUNK_OVERLAP = int(os.getenv('CONTEXT_CHUNK_OVERLAP', 150))

# ============================================
# OPENROUTER CONFIGURATION (LLM gratuita para aquecimento)
# ============================================
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'meta-llama/llama-3.1-8b-instruct:free')
