# Generated by Django 6.0.1 on 2026-01-31 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_numero', models.CharField(choices=[('novo', 'Novo (até 2 meses) - 40-50 msg/dia'), ('recente', 'Recente (2-6 meses) - 100-200 msg/dia'), ('medio', 'Médio (6-12 meses) - 200-300 msg/dia'), ('antigo', 'Antigo (+2 anos) - 400-500 msg/dia')], default='novo', max_length=20, verbose_name='Idade do Número')),
                ('limite_diario', models.IntegerField(default=50, verbose_name='Limite Diário de Mensagens')),
                ('delay_minimo', models.IntegerField(default=15, verbose_name='Delay Mínimo (segundos)')),
                ('delay_maximo', models.IntegerField(default=60, verbose_name='Delay Máximo (segundos)')),
                ('pausa_apos_mensagens', models.IntegerField(default=20, verbose_name='Pausar após X mensagens')),
                ('duracao_pausa', models.IntegerField(default=300, verbose_name='Duração da pausa (segundos)')),
                ('horario_inicio', models.TimeField(default='08:00', verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(default='20:00', verbose_name='Horário de Fim')),
                ('enviar_apenas_dias_uteis', models.BooleanField(default=False)),
                ('max_tentativas_por_contato', models.IntegerField(default=3, verbose_name='Máx. tentativas por contato')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_disparo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Disparo',
                'verbose_name_plural': 'Configurações de Disparo',
            },
        ),
        migrations.CreateModel(
            name='InstanciaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Instância')),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('qr_code', 'Aguardando QR Code')], default='disconnected', max_length=20)),
                ('numero_conectado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Conectado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='CampanhaDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('usar_nome_cliente', models.BooleanField(default=True, verbose_name='Chamar cliente pelo nome')),
                ('total_contatos', models.IntegerField(default=0)),
                ('enviados', models.IntegerField(default=0)),
                ('entregues', models.IntegerField(default=0)),
                ('lidos', models.IntegerField(default=0)),
                ('respondidos', models.IntegerField(default=0)),
                ('falhas', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('busca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='clientes.buscacliente', verbose_name='Lista de Clientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='disparo.instanciawhatsapp')),
            ],
            options={
                'verbose_name': 'Campanha de Disparo',
                'verbose_name_plural': 'Campanhas de Disparo',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('mensagem_enviada', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('respondido', 'Respondido'), ('falha', 'Falha'), ('bloqueado', 'Número Bloqueado'), ('invalido', 'Número Inválido')], default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.IntegerField(default=0)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='disparo.campanhadisparo')),
            ],
            options={
                'verbose_name': 'Log de Envio',
                'verbose_name_plural': 'Logs de Envio',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ContatoBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('motivo', models.CharField(choices=[('opt_out', 'Pediu para sair'), ('bloqueou', 'Bloqueou o número'), ('invalido', 'Número inválido'), ('sem_whatsapp', 'Não tem WhatsApp'), ('manual', 'Removido manualmente')], max_length=20)),
                ('data_bloqueio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_bloqueados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato Bloqueado',
                'verbose_name_plural': 'Contatos Bloqueados',
                'unique_together': {('usuario', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EstatisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('mensagens_enviadas', models.IntegerField(default=0)),
                ('mensagens_entregues', models.IntegerField(default=0)),
                ('mensagens_falha', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatística Diária',
                'verbose_name_plural': 'Estatísticas Diárias',
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
