# Generated by Django 5.2.10 on 2026-01-31 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('disparo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhadisparo',
            name='busca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='clientes.buscacliente', verbose_name='Lista de Clientes'),
        ),
    ]
