# Generated by Django 6.0.1 on 2026-01-31 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BuscaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_busca', models.CharField(max_length=255, verbose_name='Termo de busca')),
                ('fonte', models.CharField(choices=[('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn')], default='google_maps', max_length=20)),
                ('apenas_whatsapp', models.BooleanField(default=False, verbose_name='Apenas com WhatsApp')),
                ('apenas_email', models.BooleanField(default=False, verbose_name='Apenas com Email')),
                ('apenas_endereco', models.BooleanField(default=False, verbose_name='Apenas com Endereço')),
                ('data_busca', models.DateTimeField(auto_now_add=True)),
                ('total_resultados', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscas', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cidade')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.estado')),
            ],
            options={
                'verbose_name': 'Busca de Cliente',
                'verbose_name_plural': 'Buscas de Clientes',
                'ordering': ['-data_busca'],
            },
        ),
        migrations.CreateModel(
            name='ClienteEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('total_avaliacoes', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('busca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.buscacliente')),
            ],
            options={
                'verbose_name': 'Cliente Encontrado',
                'verbose_name_plural': 'Clientes Encontrados',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='clientes.estado'),
        ),
    ]
