# Generated by Django 6.0.1 on 2026-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscacliente',
            name='data_enriquecimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buscacliente',
            name='enriquecida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buscacliente',
            name='total_qualificados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='classificacao',
            field=models.CharField(choices=[('quente', 'Lead Quente'), ('morno', 'Lead Morno'), ('frio', 'Lead Frio'), ('descartado', 'Descartado')], db_index=True, default='frio', max_length=20),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='cnae_descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='data_enriquecimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='enriquecido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='erro_enriquecimento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='lead_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='porte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='score_detalhes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='situacao_cadastral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='tem_redes_sociais',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='tem_website',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='whatsapp_existe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteencontrado',
            name='whatsapp_validado',
            field=models.BooleanField(default=False),
        ),
    ]
