# Generated by Django 6.0.1 on 2026-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_buscacliente_data_enriquecimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscacliente',
            name='max_resultados',
            field=models.IntegerField(default=50, verbose_name='Max. Resultados'),
        ),
    ]
